name: halalbazaar
description: Community and location based app that will help find listing, and post listings for various products (selling a car, selling a phone, etc) and services (tax filing service, cleaning service, etc)

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.5+58

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.1
  clippy_flutter: ^1.1.0
  flutter_swiper: ^1.1.6
  provider: ^4.0.0
  flushbar: ^1.10.2
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.1.1
  firebase_auth: 0.15.3
  location: ^2.4.0
  google_maps_flutter: ^0.5.28+1
  image_picker: ^0.6.3+4
  path_provider: ^1.6.1
  http: ^0.12.0+4
  geocoder: ^0.2.1
  geoflutterfire: ^2.1.0
  geolocator: ^5.3.2+2
  shared_preferences: ^0.5.6+3
  url_launcher: ^5.4.2
  get_it: ^4.0.1
  font_awesome_flutter: ^8.7.0
  fancy_bottom_navigation: ^0.3.2
  moneytextformfield: ^0.3.5+1
  firebase_core: 0.4.4
  firebase_storage: ^3.1.5
  image_cropper: ^1.2.1
  multi_image_picker: ^4.6.5+rc.1
  carousel_slider: ^1.4.1
  fab_circular_menu: ^1.0.0
  solid_bottom_sheet: ^0.1.9
  fancy_dialog: ^1.0.3
  cached_network_image: ^2.1.0+1
  uuid: ^2.0.4
  flutter_email_sender: ^3.0.1
  data_connection_checker: ^0.3.4
  connectivity: ^0.4.8+2
  flutter_html: ^0.11.1
  permission_handler: ^5.0.1+1
  native_state: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/hblogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/google_logo.png
    - assets/images/fblogo.png
    - assets/images/hblogo.png
    - assets/images/HLogotransparent.png
    - assets/images/HLogowithbackground.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
